# Generated by Django 3.1 on 2020-08-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='transaction',
            field=models.CharField(choices=[('', ''), ('BUY', 'Buy'), ('SELL', 'Sell')], default='', max_length=10, verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Stock Name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='oid',
            field=models.CharField(max_length=200, unique=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Stock Price'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Stock quantity'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.CharField(max_length=200, verbose_name='User'),
        ),
    ]
