# Generated by Django 3.1 on 2020-08-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20200831_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='transaction',
        ),
    ]
