# Generated by Django 3.1 on 2020-09-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_trade_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='transaction',
        ),
    ]
