# Generated by Django 3.1 on 2020-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_remove_trade_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stock_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Stock Price'),
        ),
    ]
