# Generated by Django 3.1 on 2020-09-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_trade_stock_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='stock_investment',
        ),
    ]
